name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # ou master, selon votre branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Le dossier qui contient les fichiers à déployer
          branch: gh-pages # La branche où déployer